# Generated by Django 3.0.7 on 2021-03-21 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sdcform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.TextField()),
                ('addition', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormFillerID',
            fields=[
                ('identifier', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12)])),
            ],
        ),
        migrations.CreateModel(
            name='PatientID',
            fields=[
                ('ohip', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='SDCFormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('clinician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.FormFillerID')),
                ('diagnostic_procedure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcform.DiagnosticProcedureID')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.PatientID')),
                ('sdcform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcform.SDCForm')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(blank=True, null=True)),
                ('sdcformresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.SDCFormResponse')),
                ('sdcquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcform.SDCQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdcformresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.SDCFormResponse')),
                ('sdcquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcform.SDCQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdcformresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.SDCFormResponse')),
                ('sdcquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcform.SDCQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('sdcformresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.SDCFormResponse')),
                ('sdcquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcform.SDCQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('sdcformresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.SDCFormResponse')),
                ('sdcquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdcform.SDCQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('choiceanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sdcformresponse.ChoiceAnswer')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sdcformresponse.SingleChoiceAnswer')),
            ],
            bases=('sdcformresponse.choiceanswer',),
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('choiceanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sdcformresponse.ChoiceAnswer')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choices', to='sdcformresponse.MultipleChoiceAnswer')),
            ],
            bases=('sdcformresponse.choiceanswer',),
        ),
    ]
