# Generated by Django 3.0.7 on 2021-03-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticProcedureID',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SDCForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diagnostic_procedure_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sdcform.DiagnosticProcedureID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sdcform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sdcform.SDCForm')),
            ],
        ),
        migrations.CreateModel(
            name='SDCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('controller_answer_enabler', models.TextField(blank=True, default=None, null=True)),
                ('controller', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdcform.SDCQuestion')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sdcform.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('input_type', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('sdcquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sdcform.SDCQuestion')),
            ],
        ),
    ]
