# Generated by Django 3.0.7 on 2021-02-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticprocedureid',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
