# Generated by Django 3.0.7 on 2021-03-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdcform',
            name='diagnostic_procedure_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdcform.DiagnosticProcedureID'),
        ),
    ]
