# Generated by Django 3.1.7 on 2021-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcform', '0002_auto_20210222_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticprocedureid',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
