# Generated by Django 3.0.7 on 2021-04-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcform', '0002_auto_20210322_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sdcquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sdcquestion',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
